name: quadruped_pympc_ros2_humble_env
channels:
- conda-forge
- nvidia/label/cuda-12.4.1
- robostack-staging
dependencies:
- pip
- python
- casadi
- numpy
- matplotlib
- nvidia/label/cuda-12.4.0::cuda-nvcc
- jax[cuda12]
- meshcat-python 
- scipy==1.15.1  
- pinocchio
- adam-robotics[all]
- ros-humble-desktop
- ros-humble-plotjuggler-ros
- ros-humble-rmw-cyclonedds-cpp
- ros-humble-rosidl-generator-dds-idl
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- tqdm
- gymnasium
- pip:
  - mujoco
  - readchar
  - liecasadi

